### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by cv21** [chapsuk/mserv#10]
Nowaday you could not do anything when your http.ListenAndServe func got an error. For example, you might not be able to shut down your service.

**Comment by chapsuk** [comment]
Hi, @cv21 👋 

Thanks for feedback, i think you're right and current error handling (log write) not ideal.
I reviewed the ability to return errors and added the ability to receive errors when starting and stopping a group of servers. New tag [v1.0.0](https://github.com/chapsuk/mserv/releases/tag/v1.0.0).

Feel free for reopen if needed.

**Comment by chapsuk** [comment]
https://github.com/chapsuk/mserv/commit/c04d8dbb4bca23b7b794252dcb3a7382162a80b6
