### ISSUE TITLE
Please, make vX.Y.Z versioning

### ISSUE THREAD

**Issue by im-kulikov** [chapsuk/mserv#5]
https://semver.org

`go mod -init -module github.com/some/repo`

can't parse version `v0.1`, `v0.2` or `v0.3`

```
module github.com/some/repo

require (
	github.com/chapsuk/mserv v0.0.0-20180706125941-107033951ceb
	...
)
```

For example, `github.com/pkg/errors`:

```
module github.com/some/repo

require (
	...
	github.com/pkg/errors v0.8.0
	...
)
```

**Comment by chapsuk** [comment]
Thanks, fixed!
 https://github.com/chapsuk/mserv/releases/tag/v0.3.0
